use crate::actors::agent_actor::model::SelfUpdateRequest;
use crate::actors::context_actor::model::GetSkillDirRequest;
use crate::actors::storage_actor::model::context::ContextCreateRequest;
use crate::actors::storage_actor::model::workflow::WorkflowCreateRequest;
use crate::actors::tools_actor::model::ToolExecutionContext;
use crate::actors::tools_actor::runtime::tool_template;
use crate::actors::workflow_actor::model::{
    ListAgentsRequest, SelfShowRequest, TaskFinishRequest, WorkflowStartRequest,
};
use genai::chat::Tool;
use serde_json::{Value, json};
use std::collections::HashMap;

pub fn uuid_generate() -> Tool {
    tool_template(
        "prismagent_uuid_generate",
        "Generate explicit petname UUID candidates for PrismAgent objects. Use these UUIDs in agent/context/workflow/trigger creation and write them into workflow/context content.",
        json!({
            "type": "object",
            "properties": {
                "count": {"type": "integer", "description": "Number of UUID candidates to generate, 1 to 64"}
            },
            "required": ["count"]
        }),
    )
}

pub fn profile_list() -> Tool {
    tool_template(
        "prismagent_profile_list",
        "List available PrismAgent profile names. Use this before selecting an agent or coordinator profile.",
        json!({
            "type": "object",
            "properties": {},
            "required": []
        }),
    )
}

pub fn skill_dir_get() -> Tool {
    tool_template(
        "prismagent_skill_dir_get",
        "Get the filesystem path to a skill directory. Use this together with fs_file_read/fs_tree_list to read skill files (SKILL.md and any supporting files). Returns an error if the skill is not found.",
        json!({
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Skill name to locate"}
            },
            "required": ["name"]
        }),
    )
}

pub fn agent_list() -> Tool {
    tool_template(
        "prismagent_agent_list",
        "List agents in the current workspace with their metadata and context_refs/context_out existence. Coordinators use this to inspect workflow state before updating agents or triggers.",
        json!({
            "type": "object",
            "properties": {},
            "required": []
        }),
    )
}

pub fn context_create() -> Tool {
    tool_template(
        "prismagent_context_create",
        "Create a new context document in the current workspace with an explicit UUID previously generated by prismagent_uuid_generate.",
        json!({
            "type": "object",
            "properties": {
                "uuid": {"type": "string", "description": "Explicit context UUID"},
                "title": {"type": "string", "description": "Human-readable context title"},
                "content": {"type": "string", "description": "Markdown context content. Include every relevant agent_uuid, context_uuid, workflow_uuid, and expected output UUID that downstream agents or coordinators will need."}
            },
            "required": ["uuid", "title", "content"]
        }),
    )
}

pub fn workflow_create() -> Tool {
    tool_template(
        "prismagent_workflow_create",
        "Create a new workflow document in the current workspace with an explicit UUID previously generated by prismagent_uuid_generate.",
        json!({
            "type": "object",
            "properties": {
                "uuid": {"type": "string", "description": "Explicit workflow UUID"},
                "title": {"type": "string", "description": "Human-readable workflow title"},
                "content": {"type": "string", "description": "TOML DAG workflow specification. Include [workflow], [[context]], [[agent]], and [[step]] sections. [workflow].uuid/title must match this request."},
                "metadata": {
                    "type": "object",
                    "additionalProperties": {"type": "string"},
                    "description": "Optional workflow metadata"
                }
            },
            "required": ["uuid", "title", "content"]
        }),
    )
}

pub fn workflow_start() -> Tool {
    tool_template(
        "prismagent_workflow_start",
        "Start a TOML DAG workflow. PrismAgent executes the workflow with code, without creating an LLM coordinator.",
        json!({
            "type": "object",
            "properties": {
                "workflow_uuid": {"type": "string", "description": "Workflow UUID to run. The workflow document content must be TOML and contain [workflow].planner_uuid."}
            },
            "required": ["workflow_uuid"]
        }),
    )
}

pub fn self_show() -> Tool {
    tool_template(
        "prismagent_self_show",
        "Show stable metadata for the current caller agent, including context_refs and context_out existence.",
        json!({
            "type": "object",
            "properties": {},
            "required": []
        }),
    )
}

pub fn self_update() -> Tool {
    tool_template(
        "prismagent_self_update",
        "Update safe mutable metadata for the current caller agent. Use auto_loop=false for self-rescue or auto_loop_message for cleanup behavior. This tool cannot modify context_refs/context_out; coordinators must use prismagent_agent_update for workflow topology changes.",
        json!({
            "type": "object",
            "properties": {
                "auto_loop": {
                    "type": "boolean",
                    "description": "Only false is allowed. Use only to stop accidental infinite loops; normal task completion must use prismagent_task_finish."
                },
                "auto_loop_message": {
                    "type": "string",
                    "description": "Replacement auto-loop message for the current agent"
                }
            },
            "required": []
        }),
    )
}

pub fn task_finish() -> Tool {
    tool_template(
        "prismagent_task_finish",
        "Mark the current agent task as finished by disabling its auto-loop runtime flag.",
        json!({
            "type": "object",
            "properties": {
                "summary": {"type": "string", "description": "Short summary of the completed task"},
                "context_outputs": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Context uuids produced for this task, if any"
                }
            },
            "required": ["summary"]
        }),
    )
}

pub async fn execute_agent_list(ctx: ToolExecutionContext, _args: Value) -> String {
    match ctx
        .handles
        .workflow
        .list_agents(ListAgentsRequest {
            workspace_uuid: ctx.workspace_uuid.clone(),
        })
        .await
    {
        Ok(response) => json!({"status": "ok", "agents": response.agents}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_profile_list(ctx: ToolExecutionContext, _args: Value) -> String {
    match ctx.handles.profile.list_profiles().await {
        Ok(profiles) => json!({"status": "ok", "profiles": profiles}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_skill_dir_get(ctx: ToolExecutionContext, args: Value) -> String {
    let request = GetSkillDirRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        name: string_arg(&args, "name").unwrap_or_default(),
    };
    match ctx.handles.context.get_skill_dir(request).await {
        Ok(path) => json!({"status": "ok", "path": path}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_context_create(ctx: ToolExecutionContext, args: Value) -> String {
    let request = ContextCreateRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        uuid: string_arg(&args, "uuid").unwrap_or_default(),
        title: string_arg(&args, "title").unwrap_or_else(|| "Untitled context".to_string()),
        content: string_arg(&args, "content").unwrap_or_default(),
    };
    match ctx.handles.workflow.context_create(request).await {
        Ok(context) => json!({
            "status": "ok",
            "context_uuid": context.uuid,
            "title": context.title,
        })
        .to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_workflow_create(ctx: ToolExecutionContext, args: Value) -> String {
    let request = WorkflowCreateRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        uuid: string_arg(&args, "uuid").unwrap_or_default(),
        title: string_arg(&args, "title").unwrap_or_else(|| "Untitled workflow".to_string()),
        content: string_arg(&args, "content").unwrap_or_default(),
        metadata: metadata_arg(&args),
    };
    match ctx.handles.workflow.workflow_create(request).await {
        Ok(workflow) => json!({
            "status": "ok",
            "workflow_uuid": workflow.uuid,
            "title": workflow.title,
        })
        .to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_uuid_generate(ctx: ToolExecutionContext, args: Value) -> String {
    let count = args.get("count").and_then(Value::as_u64).unwrap_or(1) as usize;
    match ctx.handles.workflow.uuid_generate(count).await {
        Ok(uuids) => json!({"status": "ok", "uuids": uuids}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_workflow_start(ctx: ToolExecutionContext, args: Value) -> String {
    let request = WorkflowStartRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        workflow_uuid: string_arg(&args, "workflow_uuid").unwrap_or_default(),
    };
    match ctx.handles.workflow.workflow_start(request).await {
        Ok(runtime) => json!({"status": "ok", "runtime": runtime}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_self_show(ctx: ToolExecutionContext, _args: Value) -> String {
    let request = SelfShowRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        agent_uuid: ctx.caller_agent_uuid.clone(),
    };
    match ctx.handles.workflow.self_show(request).await {
        Ok(response) => json!({
            "status": "ok",
            "agent": response,
        })
        .to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_self_update(ctx: ToolExecutionContext, args: Value) -> String {
    if args.get("context_refs").is_some() || args.get("context_out").is_some() {
        return json!({
            "status": "error",
            "error": "prismagent_self_update cannot modify context_refs/context_out; ask the coordinator to use prismagent_agent_update"
        })
        .to_string();
    }
    let request = SelfUpdateRequest {
        agent_uuid: ctx.caller_agent_uuid.clone(),
        context_refs: None,
        context_out: None,
        auto_loop: args.get("auto_loop").and_then(Value::as_bool),
        auto_loop_message: string_arg(&args, "auto_loop_message"),
    };
    match ctx.handles.agent.self_update(request).await {
        Ok(agent) => json!({
            "status": "ok",
            "agent_uuid": agent.uuid,
            "auto_loop": agent.auto_loop,
        })
        .to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_task_finish(ctx: ToolExecutionContext, args: Value) -> String {
    let summary = string_arg(&args, "summary").unwrap_or_else(|| "task finished".to_string());
    let context_outputs = string_array_arg(&args, "context_outputs");
    match ctx
        .handles
        .workflow
        .task_finish(TaskFinishRequest {
            workspace_uuid: ctx.workspace_uuid.clone(),
            agent_uuid: ctx.caller_agent_uuid.clone(),
            summary,
            context_outputs,
        })
        .await
    {
        Ok(response) => json!({
            "status": "ok",
            "agent_uuid": response.agent_uuid,
            "auto_loop": response.auto_loop,
            "context_outputs": response.context_outputs,
        })
        .to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

fn string_arg(args: &Value, name: &str) -> Option<String> {
    args.get(name)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
}

fn string_array_arg(args: &Value, name: &str) -> Vec<String> {
    args.get(name)
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}

fn metadata_arg(args: &Value) -> HashMap<String, String> {
    args.get("metadata")
        .and_then(Value::as_object)
        .into_iter()
        .flat_map(|object| object.iter())
        .filter_map(|(key, value)| value.as_str().map(|value| (key.clone(), value.to_string())))
        .collect()
}
