use crate::actors::agent_actor::model::{MessageBody, SendMessageRequest, SelfUpdateRequest};
use crate::actors::context_actor::model::GetSkillDirRequest;
use crate::actors::storage_actor::model::agent::AgentCreateRequest;
use crate::actors::storage_actor::model::context::ContextCreateRequest;
use crate::actors::storage_actor::model::workflow::WorkflowCreateRequest;
use crate::actors::tools_actor::model::ToolExecutionContext;
use crate::actors::tools_actor::runtime::tool_template;
use crate::actors::workflow_actor::model::{
    ListAgentsRequest, SelfShowRequest, TaskFinishRequest, WorkflowStartRequest,
    WorkflowTriggerCreateRequest,
};
use crate::stdlib_assets::DEFAULT_PROFILE_NAME;
use genai::chat::Tool;
use serde_json::{Value, json};
use std::collections::HashMap;

pub fn uuid_generate() -> Tool {
    tool_template(
        "prismagent_uuid_generate",
        "Generate explicit petname UUID candidates for PrismAgent objects. Use these UUIDs in agent/context/workflow/trigger creation and write them into workflow/context content.",
        json!({
            "type": "object",
            "properties": {
                "count": {"type": "integer", "description": "Number of UUID candidates to generate, 1 to 64"}
            },
            "required": ["count"]
        }),
    )
}

pub fn profile_list() -> Tool {
    tool_template(
        "prismagent_profile_list",
        "List available PrismAgent profile names. Use this before selecting an agent or coordinator profile.",
        json!({
            "type": "object",
            "properties": {},
            "required": []
        }),
    )
}

pub fn skill_dir_get() -> Tool {
    tool_template(
        "prismagent_skill_dir_get",
        "Get the filesystem path to a skill directory. Use this together with fs_file_read/fs_tree_list to read skill files (SKILL.md and any supporting files). Returns an error if the skill is not found.",
        json!({
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Skill name to locate"}
            },
            "required": ["name"]
        }),
    )
}

pub fn agent_create() -> Tool {
    tool_template(
        "prismagent_agent_create",
        "Create a new PrismAgent agent in the current workspace with an explicit UUID previously generated by prismagent_uuid_generate.",
        json!({
            "type": "object",
            "properties": {
                "uuid": {"type": "string", "description": "Explicit agent UUID"},
                "name": {"type": "string", "description": "Human-readable agent name describing its responsibility"},
                "profile": {"type": "string", "description": "Profile name, e.g. default, planner, executor"},
                "context_refs": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Context uuids this agent should use as task input"
                },
                "context_out": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Context uuids this agent is expected to produce"
                }
            },
            "required": ["uuid", "name"]
        }),
    )
}

pub fn agent_list() -> Tool {
    tool_template(
        "prismagent_agent_list",
        "List agents in the current workspace with their metadata and context_refs/context_out existence. Coordinators use this to inspect workflow state before updating agents or triggers.",
        json!({
            "type": "object",
            "properties": {},
            "required": []
        }),
    )
}

pub fn context_create() -> Tool {
    tool_template(
        "prismagent_context_create",
        "Create a new context document in the current workspace with an explicit UUID previously generated by prismagent_uuid_generate.",
        json!({
            "type": "object",
            "properties": {
                "uuid": {"type": "string", "description": "Explicit context UUID"},
                "title": {"type": "string", "description": "Human-readable context title"},
                "content": {"type": "string", "description": "Markdown context content. Include every relevant agent_uuid, context_uuid, workflow_uuid, and expected output UUID that downstream agents or coordinators will need."}
            },
            "required": ["uuid", "title", "content"]
        }),
    )
}

pub fn workflow_create() -> Tool {
    tool_template(
        "prismagent_workflow_create",
        "Create a new workflow document in the current workspace with an explicit UUID previously generated by prismagent_uuid_generate.",
        json!({
            "type": "object",
            "properties": {
                "uuid": {"type": "string", "description": "Explicit workflow UUID"},
                "title": {"type": "string", "description": "Human-readable workflow title"},
                "content": {"type": "string", "description": "Workflow description, preferably markdown with Mermaid when useful. Include all planned agent_uuid, context_uuid, workflow_uuid, trigger_uuid, dependencies, and expected context_out UUIDs in the body so the coordinator can operate deterministically."},
                "metadata": {
                    "type": "object",
                    "additionalProperties": {"type": "string"},
                    "description": "Optional workflow metadata"
                }
            },
            "required": ["uuid", "title", "content"]
        }),
    )
}

pub fn workflow_start() -> Tool {
    tool_template(
        "prismagent_workflow_start",
        "Start a workflow by creating and messaging a coordinator agent. The coordinator is not auto-loop by default.",
        json!({
            "type": "object",
            "properties": {
                "workflow_uuid": {"type": "string", "description": "Workflow UUID to run"},
                "coordinator_uuid": {"type": "string", "description": "Explicit UUID for the coordinator agent"},
                "coordinator_name": {"type": "string", "description": "Human-readable coordinator agent name"},
                "coordinator_profile": {"type": "string", "description": "Profile name for coordinator, defaults to coordinator"}
            },
            "required": ["workflow_uuid", "coordinator_uuid", "coordinator_name"]
        }),
    )
}

pub fn trigger_create() -> Tool {
    tool_template(
        "prismagent_trigger_create",
        "Register an OR workflow trigger for the current coordinator. When any watched context UUID is created, PrismAgent sends this coordinator a message.",
        json!({
            "type": "object",
            "properties": {
                "uuid": {"type": "string", "description": "Explicit trigger UUID"},
                "workflow_uuid": {"type": "string", "description": "Workflow UUID this trigger belongs to"},
                "context_uuids": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Watched context UUIDs. OR semantics: any one created context fires the trigger."
                },
                "message": {"type": "string", "description": "Message sent when the trigger fires. {context_uuid} and {workflow_uuid} are substituted."}
            },
            "required": ["uuid", "workflow_uuid", "context_uuids", "message"]
        }),
    )
}

pub fn self_show() -> Tool {
    tool_template(
        "prismagent_self_show",
        "Show stable metadata for the current caller agent, including context_refs and context_out existence.",
        json!({
            "type": "object",
            "properties": {},
            "required": []
        }),
    )
}

pub fn agent_message_send() -> Tool {
    tool_template(
        "prismagent_agent_message_send",
        "Send a text message to another PrismAgent agent in the current workspace. The target agent UUID must be known from workflow/context content or prior tool results.",
        json!({
            "type": "object",
            "properties": {
                "agent_uuid": {"type": "string", "description": "Target agent UUID"},
                "message": {"type": "string", "description": "Text message to send to the target agent"}
            },
            "required": ["agent_uuid", "message"]
        }),
    )
}

pub fn agent_terminate() -> Tool {
    tool_template(
        "prismagent_agent_terminate",
        "Ask another PrismAgent agent to cleanly terminate on its next auto-loop continuation by replacing its auto_loop_message. This does not interrupt the current step and does not enable auto_loop.",
        json!({
            "type": "object",
            "properties": {
                "agent_uuid": {"type": "string", "description": "Target agent UUID"},
                "reason": {"type": "string", "description": "Reason for termination or workflow cancellation"},
                "instructions": {"type": "string", "description": "Optional cleanup instructions for the target agent"}
            },
            "required": ["agent_uuid", "reason"]
        }),
    )
}

pub fn agent_update() -> Tool {
    tool_template(
        "prismagent_agent_update",
        "Update mutable metadata for another PrismAgent agent. Coordinators should use this when changing context_refs/context_out and then register workflow triggers if needed. auto_loop can only be set to false.",
        json!({
            "type": "object",
            "properties": {
                "agent_uuid": {"type": "string", "description": "Target agent UUID"},
                "context_refs": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Replacement context UUIDs the target agent depends on"
                },
                "context_out": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Replacement context UUIDs the target agent is expected to produce"
                },
                "auto_loop": {
                    "type": "boolean",
                    "description": "Only false is allowed. Use only to stop accidental infinite loops; normal task completion must use prismagent_task_finish."
                },
                "auto_loop_message": {
                    "type": "string",
                    "description": "Replacement auto-loop message for the target agent, commonly used for clean termination or cleanup instructions"
                }
            },
            "required": ["agent_uuid"]
        }),
    )
}

pub fn self_update() -> Tool {
    tool_template(
        "prismagent_self_update",
        "Update safe mutable metadata for the current caller agent. Use auto_loop=false for self-rescue or auto_loop_message for cleanup behavior. This tool cannot modify context_refs/context_out; coordinators must use prismagent_agent_update for workflow topology changes.",
        json!({
            "type": "object",
            "properties": {
                "auto_loop": {
                    "type": "boolean",
                    "description": "Only false is allowed. Use only to stop accidental infinite loops; normal task completion must use prismagent_task_finish."
                },
                "auto_loop_message": {
                    "type": "string",
                    "description": "Replacement auto-loop message for the current agent"
                }
            },
            "required": []
        }),
    )
}

pub fn task_finish() -> Tool {
    tool_template(
        "prismagent_task_finish",
        "Mark the current agent task as finished by disabling its auto-loop runtime flag.",
        json!({
            "type": "object",
            "properties": {
                "summary": {"type": "string", "description": "Short summary of the completed task"},
                "context_outputs": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Context uuids produced for this task, if any"
                }
            },
            "required": ["summary"]
        }),
    )
}

pub async fn execute_agent_create(ctx: ToolExecutionContext, args: Value) -> String {
    let request = AgentCreateRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        uuid: string_arg(&args, "uuid").unwrap_or_default(),
        name: string_arg(&args, "name").unwrap_or_else(|| "Untitled agent".to_string()),
        profile: string_arg(&args, "profile").unwrap_or_else(|| DEFAULT_PROFILE_NAME.to_string()),
        context_refs: string_array_arg(&args, "context_refs"),
        context_out: string_array_arg(&args, "context_out"),
    };
    match ctx.handles.agent.create(request).await {
        Ok(agent) => json!({"status": "ok", "agent": agent}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_agent_list(ctx: ToolExecutionContext, _args: Value) -> String {
    match ctx
        .handles
        .workflow
        .list_agents(ListAgentsRequest {
            workspace_uuid: ctx.workspace_uuid.clone(),
        })
        .await
    {
        Ok(response) => json!({"status": "ok", "agents": response.agents}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_profile_list(ctx: ToolExecutionContext, _args: Value) -> String {
    match ctx.handles.profile.list_profiles().await {
        Ok(profiles) => json!({"status": "ok", "profiles": profiles}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_skill_dir_get(ctx: ToolExecutionContext, args: Value) -> String {
    let request = GetSkillDirRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        name: string_arg(&args, "name").unwrap_or_default(),
    };
    match ctx.handles.context.get_skill_dir(request).await {
        Ok(path) => json!({"status": "ok", "path": path}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_context_create(ctx: ToolExecutionContext, args: Value) -> String {
    let request = ContextCreateRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        uuid: string_arg(&args, "uuid").unwrap_or_default(),
        title: string_arg(&args, "title").unwrap_or_else(|| "Untitled context".to_string()),
        content: string_arg(&args, "content").unwrap_or_default(),
    };
    match ctx.handles.workflow.context_create(request).await {
        Ok(context) => json!({"status": "ok", "context": context}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_workflow_create(ctx: ToolExecutionContext, args: Value) -> String {
    let request = WorkflowCreateRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        uuid: string_arg(&args, "uuid").unwrap_or_default(),
        title: string_arg(&args, "title").unwrap_or_else(|| "Untitled workflow".to_string()),
        content: string_arg(&args, "content").unwrap_or_default(),
        metadata: metadata_arg(&args),
    };
    match ctx.handles.workflow.workflow_create(request).await {
        Ok(workflow) => json!({"status": "ok", "workflow": workflow}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_uuid_generate(ctx: ToolExecutionContext, args: Value) -> String {
    let count = args.get("count").and_then(Value::as_u64).unwrap_or(1) as usize;
    match ctx.handles.workflow.uuid_generate(count).await {
        Ok(uuids) => json!({"status": "ok", "uuids": uuids}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_workflow_start(ctx: ToolExecutionContext, args: Value) -> String {
    let request = WorkflowStartRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        workflow_uuid: string_arg(&args, "workflow_uuid").unwrap_or_default(),
        coordinator_uuid: string_arg(&args, "coordinator_uuid").unwrap_or_default(),
        coordinator_name: string_arg(&args, "coordinator_name")
            .unwrap_or_else(|| "Workflow Coordinator".to_string()),
        coordinator_profile: string_arg(&args, "coordinator_profile")
            .unwrap_or_else(|| "coordinator".to_string()),
    };
    match ctx.handles.workflow.workflow_start(request).await {
        Ok(runtime) => json!({"status": "ok", "runtime": runtime}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_trigger_create(ctx: ToolExecutionContext, args: Value) -> String {
    let request = WorkflowTriggerCreateRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        uuid: string_arg(&args, "uuid").unwrap_or_default(),
        workflow_uuid: string_arg(&args, "workflow_uuid").unwrap_or_default(),
        coordinator_agent_uuid: ctx.caller_agent_uuid.clone(),
        context_uuids: string_array_arg(&args, "context_uuids"),
        message: string_arg(&args, "message").unwrap_or_default(),
    };
    match ctx.handles.workflow.trigger_create(request).await {
        Ok(trigger) => json!({"status": "ok", "trigger": trigger}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_self_show(ctx: ToolExecutionContext, _args: Value) -> String {
    let request = SelfShowRequest {
        workspace_uuid: ctx.workspace_uuid.clone(),
        agent_uuid: ctx.caller_agent_uuid.clone(),
    };
    match ctx.handles.workflow.self_show(request).await {
        Ok(response) => json!({"status": "ok", "agent": response}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_agent_message_send(ctx: ToolExecutionContext, args: Value) -> String {
    let request = SendMessageRequest {
        agent_uuid: string_arg(&args, "agent_uuid").unwrap_or_default(),
        message_body: MessageBody {
            text: string_arg(&args, "message").unwrap_or_default(),
            attachments: Vec::new(),
        },
    };
    match ctx.handles.agent.send_message(request).await {
        Ok(()) => json!({"status": "ok"}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_agent_terminate(ctx: ToolExecutionContext, args: Value) -> String {
    let reason = string_arg(&args, "reason").unwrap_or_else(|| "workflow cancelled".to_string());
    let instructions = string_arg(&args, "instructions").unwrap_or_default();
    let cleanup_message = if instructions.is_empty() {
        format!(
            "The workflow has requested clean termination. Stop normal work, summarize partial progress, update context_refs/context_out if needed, write any required context outputs, and call prismagent_task_finish when cleanup is complete. Reason: {reason}"
        )
    } else {
        format!(
            "The workflow has requested clean termination. Stop normal work, summarize partial progress, update context_refs/context_out if needed, write any required context outputs, and call prismagent_task_finish when cleanup is complete. Reason: {reason}\n\nCleanup instructions:\n{instructions}"
        )
    };
    let request = SelfUpdateRequest {
        agent_uuid: string_arg(&args, "agent_uuid").unwrap_or_default(),
        context_refs: None,
        context_out: None,
        auto_loop: None,
        auto_loop_message: Some(cleanup_message),
    };
    match ctx.handles.agent.self_update(request).await {
        Ok(agent) => json!({"status": "ok", "agent": agent}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_agent_update(ctx: ToolExecutionContext, args: Value) -> String {
    let request = SelfUpdateRequest {
        agent_uuid: string_arg(&args, "agent_uuid").unwrap_or_default(),
        context_refs: optional_string_array_arg(&args, "context_refs"),
        context_out: optional_string_array_arg(&args, "context_out"),
        auto_loop: args.get("auto_loop").and_then(Value::as_bool),
        auto_loop_message: string_arg(&args, "auto_loop_message"),
    };
    match ctx.handles.agent.self_update(request).await {
        Ok(agent) => json!({"status": "ok", "agent": agent}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_self_update(ctx: ToolExecutionContext, args: Value) -> String {
    if args.get("context_refs").is_some() || args.get("context_out").is_some() {
        return json!({
            "status": "error",
            "error": "prismagent_self_update cannot modify context_refs/context_out; ask the coordinator to use prismagent_agent_update"
        })
        .to_string();
    }
    let request = SelfUpdateRequest {
        agent_uuid: ctx.caller_agent_uuid.clone(),
        context_refs: None,
        context_out: None,
        auto_loop: args.get("auto_loop").and_then(Value::as_bool),
        auto_loop_message: string_arg(&args, "auto_loop_message"),
    };
    match ctx.handles.agent.self_update(request).await {
        Ok(agent) => json!({"status": "ok", "agent": agent}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

pub async fn execute_task_finish(ctx: ToolExecutionContext, args: Value) -> String {
    let summary = string_arg(&args, "summary").unwrap_or_else(|| "task finished".to_string());
    let context_outputs = string_array_arg(&args, "context_outputs");
    match ctx
        .handles
        .workflow
        .task_finish(TaskFinishRequest {
            workspace_uuid: ctx.workspace_uuid.clone(),
            agent_uuid: ctx.caller_agent_uuid.clone(),
            summary,
            context_outputs,
        })
        .await
    {
        Ok(response) => json!({"status": "ok", "result": response}).to_string(),
        Err(error) => json!({"status": "error", "error": error.to_string()}).to_string(),
    }
}

fn string_arg(args: &Value, name: &str) -> Option<String> {
    args.get(name)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
}

fn string_array_arg(args: &Value, name: &str) -> Vec<String> {
    args.get(name)
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .map(str::trim)
        .filter(|value| !value.is_empty())
        .map(ToOwned::to_owned)
        .collect()
}

fn optional_string_array_arg(args: &Value, name: &str) -> Option<Vec<String>> {
    args.get(name).map(|_| string_array_arg(args, name))
}

fn metadata_arg(args: &Value) -> HashMap<String, String> {
    args.get("metadata")
        .and_then(Value::as_object)
        .into_iter()
        .flat_map(|object| object.iter())
        .filter_map(|(key, value)| value.as_str().map(|value| (key.clone(), value.to_string())))
        .collect()
}
